### ISSUE TITLE
Inversion des couleurs

### ISSUE THREAD

**Issue by vazarch2** [tristanmth/expeSC2#1]
{ word: "ROUGE", color: 'red' ,congruence_color: true},
    { word: "ROUGE", color: 'red' ,congruence_color: true},
    { word: "ROUGE", color: 'red' ,congruence_color: true},
    { word: "ROUGE", color: 'red' ,congruence_color: true},
    { word: "VERT", color: "green",congruence_color: true },
    { word: "VERT", color: "green",congruence_color: true },
    { word: "VERT", color: "green" ,congruence_color: true},
    { word: "VERT", color: "green" ,congruence_color: true},
    { word: "VERT", color: "red" ,congruence_color: false},
    { word: "ROUGE", color: "green" ,congruence_color: false},

    { word: "BLEU", color: "yellow" ,congruence_color: true},
    { word: "BLEU", color: "yellow" ,congruence_color: true},
    { word: "BLEU", color: "yellow" ,congruence_color: true},
    { word: "BLEU", color: "yellow" ,congruence_color: true},
    { word: "JAUNE", color: "blue" ,congruence_color: true},
    { word: "JAUNE", color: "blue" ,congruence_color: true},
    { word: "JAUNE", color: "blue" ,congruence_color: true},
    { word: "JAUNE", color: "blue" ,congruence_color: true},

    { word: "BLEU", color: "blue",congruence_color: false },
    { word: "JAUNE", color: "yellow" ,congruence_color: false},

On s'est pas trompé dans les congruence_color. Il faudrait inversé pour les BLEU-yellow et JAUNE-blue ?

**Comment by tristanmth** [comment]
bah non c'est bon dans ce groupe le paire congruente est rouge-vert donc c'est normal qu'il y a beaucoup de BLEU-yellow et de JAUNE-blue, mais apres on c'est peut etre trompé sur le true de congruence_color de BLEU-yellow et de JAUNE-blue?
